service: email-tracker

provider:
  name: aws
  profile: ${file(./config.yml):${opt:stage, self:provider.stage}.PROFILE}
  runtime: nodejs12.x

  environment:
    WEBHOOK: ${file(./config.yml):${opt:stage, self:provider.stage}.WEBHOOK}

functions:
  get:
    handler: handler.handler
    timeout: 30
    events:
      - http:
          path: image.png
          method: get
